<a href="https://colab.research.google.com/github/hemantrajsen/APS-Lab-/blob/main/Lab_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Warshall algorithm to find reachability between all pairs of vertices in a graph.
Problem Description:
Understand transitive closure of a graph. Use Python to compute reachability using matrix method.

#Theory
Warshall algorithm finds whether a path exists between every pair of vertices. It updates the adjacency matrix step by step. If there is a path from i to j through k, then the entry becomes 1.

## Algorithm
1. Represent graph using adjacency matrix.
2. For each intermediate vertex k
3. Check all pairs i and j
4. Update value if path exists through k
4. Repeat for all vertices


In [3]:
def warshall(graph):

    n = len(graph)

    for k in range(n):
        for i in range(n):
            for j in range(n):
                graph[i][j] = graph[i][j] or (graph[i][k] and graph[k][j])

    return graph


In [4]:
graph = [
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1],
[0, 0, 0, 0]
]

result = warshall(graph)

print("Transitive Closure Matrix:")

for row in result:
    print(row)

Transitive Closure Matrix:
[0, 1, 1, 1]
[0, 0, 1, 1]
[0, 0, 0, 1]
[0, 0, 0, 0]


Now, let's implement
1. Modify program to take matrix input from user
2. Apply algorithm on graph with 5 vertices
3. Compare Warshall with Floyd algorithm
4. Display path existence in readable format

In [20]:
# User Input Graph:
import numpy as np

v = int(input("Enter the number of Vertices: "))
print("Enter the matrix values row wise: ")
matrix = [list(map(int, input().split())) for _ in range(v)]

graph = np.array(matrix)
print("Graph Matrix:\n", graph)

Enter the number of Vertices: 5
Enter the matrix values row wise: 
0 1 1 1 1 
1 0 1 1 1 
0 1 0 1 1 
1 1 1 0 1
0 0 0 0 0 
Graph Matrix:
 [[0 1 1 1 1]
 [1 0 1 1 1]
 [0 1 0 1 1]
 [1 1 1 0 1]
 [0 0 0 0 0]]


In [21]:
# Warshall's algo with 5 vertices graph:
result = warshall(graph)

print("Transitive Closure Matrix:")

for row in result:
    print(row)

Transitive Closure Matrix:
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[0 0 0 0 0]


In [57]:
# Compare with FLyod-Warshall's Algo:
def warshall(graph):
    n = len(graph)
    reach = [row[:] for row in graph]  # copy matrix

    for k in range(n):
        for i in range(n):
            for j in range(n):
                reach[i][j] = reach[i][j] or (reach[i][k] and reach[k][j])
    return reach

# Example adjacency matrix (0/1 for reachability)
graph_bool = [
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1],
    [0, 0, 0, 0]
]

print("Warshall (Transitive Closure):")
for row in warshall(graph_bool):
    print(row)


def floyd_warshall1(dist):
    n = len(dist)
    result = [row[:] for row in dist]  # copy matrix

    for k in range(n):
        for i in range(n):
            for j in range(n):
                if result[i][k] + result[k][j] < result[i][j]:
                    result[i][j] = result[i][k] + result[k][j]
    return result

INF = float('inf')
# Example weighted adjacency matrix
graph_weighted = [
    [0,   3, INF,  7],
    [8,   0,   2, INF],
    [5, INF,   0,   1],
    [2, INF, INF,  0]
]

print("\nFloyd–Warshall (Shortest Paths):")
for row in floyd_warshall1(graph_weighted):
    print(row)


Warshall (Transitive Closure):
[0, 1, 1, 1]
[0, 0, 1, 1]
[0, 0, 0, 1]
[0, 0, 0, 0]

Floyd–Warshall (Shortest Paths):
[0, 3, 5, 6]
[5, 0, 2, 3]
[3, 6, 0, 1]
[2, 5, 7, 0]


## Find shortest paths between all pairs of vertices using Floyd Warshall algorithm.

#Understand all pairs shortest path problem. Implement dynamic programming approach in Python.

* Given a weighted graph with positive or negative edge weights, find
shortest distances between every pair of vertices.

# Theory
Floyd Warshall algorithm computes shortest paths between all pairs of nodes. It updates the distance matrix by checking if a shorter path exists through an intermediate vertex. Works with negative weights but fails with negative cycles.

Algorithm
1. Represent graph using distance matrix.
2. Initialize matrix with given weights.
3. Set distance of node to itself as 0.
4. For each intermediate vertex k
5. Update distance[i][j] = min(distance[i][j], distance[i][k] + distance[k][j])
6. Repeat for all vertices

In [36]:
def floyd_warshall(graph):

    n = len(graph)

    dist = []
    for i in range(n):
        dist.append(graph[i][:])

    for k in range(n):
        for i in range(n):
            for j in range(n):
                if dist[i][k] + dist[k][j] < dist[i][j]:
                    dist[i][j] = dist[i][k] + dist[k][j]

    if dist[i][i] < 0:
      print("Negative Cycle Detected!!\n")

    return dist



In [55]:
INF = float('inf')

graph1 = [
[0, 3, INF, 7],
[8, 0, 2, INF],
[5, INF, 0, 1],
[2, INF, INF, 0]
]

result = floyd_warshall(graph1)

print("Shortest distance matrix:")

for row in result:
    print(row)

Shortest distance matrix:
[0, 3, 5, 6]
[5, 0, 2, 3]
[3, 6, 0, 1]
[2, 5, 7, 0]


# Excercise
1. Take matrix input from user
2. Detect negative cycle in graph
3. Print shortest path between two given vertices
4. Compare with Dijkstra algorithm

In [41]:
# User Input Matrix:
INF = float('inf')

v = int(input("Enter the number of Vertices: "))
graph2 = []

for i in range(v):
  row = input().split()
  row_int = [INF if val == "INF" else int(val) for val in row]
  graph2.append(row_int)

print("\nGraph Matrix:")
for row in graph2:
  print(row)

Enter the number of Vertices: 4
0 3 -1 7
8 0 2 -2
5 -1 0 1 
-3 2 1 0

Graph Matrix:
[0, 3, -1, 7]
[8, 0, 2, -2]
[5, -1, 0, 1]
[-3, 2, 1, 0]


In [42]:
# Negative cycle detection:
result = floyd_warshall(graph2)

print("Shortest distance matrix:")

for row in result:
    print(row)

Negative Cycle Detected!!

Shortest distance matrix:
[-7, -9, -8, -11]
[-5, -7, -6, -9]
[-6, -8, -7, -10]
[-10, -12, -11, -14]


In [56]:
# Compare with Dijkstra Algorithm:

# Result from the Floyd Algo:
result = floyd_warshall(graph1)

print("Floyd-Warshall Result:")

for row in result:
    print(row)

# Dijkstra Algo:
import heapq

def dijkstra(graph, src):
    n = len(graph)
    dist = [float('inf')] * n
    dist[src] = 0
    pq = [(0, src)]  # (distance, vertex)

    while pq:
        d, u = heapq.heappop(pq)
        if d > dist[u]:
            continue
        for v, w in graph[u]:
            if dist[u] + w < dist[v]:
                dist[v] = dist[u] + w
                heapq.heappush(pq, (dist[v], v))
    return dist

# Example graph as adjacency list
graph = {
    0: [(1, 3), (3, 7)],
    1: [(0, 8), (2, 2)],
    2: [(0, 5), (3, 1)],
    3: [(0, 2)]
}

v = 4
for s in range(v):
    print(f"\nDijkstra Result from source {s}:")
    print(dijkstra(graph, s))

Floyd-Warshall Result:
[0, 3, 5, 6]
[5, 0, 2, 3]
[3, 6, 0, 1]
[2, 5, 7, 0]

Dijkstra Result from source 0:
[0, 3, 5, 6]

Dijkstra Result from source 1:
[5, 0, 2, 3]

Dijkstra Result from source 2:
[3, 6, 0, 1]

Dijkstra Result from source 3:
[2, 5, 7, 0]
